### ISSUE TITLE
Run CLDFBENCH to check this on your own

### ISSUE THREAD

**Issue by LinguList** [lexibank/dagloans#8]
@ilchec, can you try and run this on your own?

```
$ git clone https://github.com/lexibank/dagloans/
$ cd dagloans
$ pip install -e ./
$ cldfbench catconfig
$ cldfbench lexibank.makecldf dagloans --dev
```

Please use a virtual environment for Python, to avoidi clashes.

**Comment by ilchec** [comment]
@LinguList I get this error: ERROR: pyglottolog 3.2.2 has requirement clldutils>=3.5.2, but you'll have clldutils 3.5.0 which is incompatible. How do I update it? 

The last two commands didn't work...

Sorry for the late response, I don't get notifications from this branch for some reason, they all came today at once and I got like 5 emails with your posts from 2 weeks ago!

**Comment by xrotwang** [comment]
@ilchec you'd have to run `pip install clldutils==3.5.2`. Sorry, I just released a new `pyglottolog` version yesterday, which bumped the required version of `clldutils`.

**Comment by ilchec** [comment]
@xrotwang Thanks! Updated! "cldfbench catconfig" still doesn't work though, command not found.

**Comment by xrotwang** [comment]
@ilchec you did install `cldfbench`, right? Maybe you'll have to re-install (implicitly, as requirement of pylexibank):
```
pip install pylexibank
```

**Comment by ilchec** [comment]
@xrotwang Yes, I did. I got back my miniconda and tried to run this in a venv, seems to work (I had to delete the miniconda because it was conflicting with Flutter that I started to learn recently...).

Now the last command results in an error "raise ValueError('Concepticon ID / Gloss mismatch %s != %s' % (ValueError: Concepticon ID / Gloss mismatch BOAR (MALE PIG) != BOAR".

Should I fix the entry myself (where?) or should I do something else?

**Comment by LinguList** [comment]
And please use a virtusl environment, if you did not do so by now.

**Comment by ilchec** [comment]
@LinguList Yep, now I did and it works (except for the BOAR part).

**Comment by LinguList** [comment]
Yes, please check with the actual concepticon for the values (either
https://concepticon.clld.org or https://digling.org/calc/concepticon/).
If they show the wrong value, check with the most recent version on
github at concepticon/concepticon-data

**Comment by LinguList** [comment]
Or do you have a local version of concepticon on your machine, which has
not an updated concept? I did not run in any errors, when adding the
concept lists today...

**Comment by ilchec** [comment]
@LinguList I guess I am not supposed to have a version of concepticon in this venv, I've just made it and only installed what you've listed in this issue. Where am I supposed to change the entry? _concepts.tsv_ has BOAR (MALE PIG) in it, so it must be the concepticon counterpart...

**Comment by ilchec** [comment]
So I ran a "pip install pyconcepticon" and then tried to update it explicitly with "pip install --upgrade pyconcepticon" and the error is still there... But at least now I must have the latest version.

**Comment by LinguList** [comment]
it is not pyconcoepticon, it is the local concepticon, which you have on your machine. we separate data and code. Currently, concepticon expects [BOAR (MALE PIG)](https://concepticon.clld.org/parameters?sSearch_0=1348).

**Comment by LinguList** [comment]
So you do not seem to have the correct version of concepticon data on your system. 

You can run in your venve:

```
$ cldfbench catconfig
```

to receive a fresh version of concepticon.

**Comment by ilchec** [comment]
@LinguList How can I update it then? Sorry, I seem to ask kind of lame questions.

**Comment by ilchec** [comment]
But that's literally what I've just done!

**Comment by LinguList** [comment]
Look, concepticon-data is a repository with all concepticon data. catconfig downloads it to a config directory on your system (something like .config/cldfbench). The version you have is probably too old, but it is the last official version, so you need to clone concepticon directly and then add the path of the clone to your config file (that is different across systems, but it is the same on all macs, so you can find it by searching for concepticon-data in your system.

Once you found the config file, please find the concepticon-data folder on your system, and then check with git which branch is checked out:

```
$ git branch
```

I suppose it is an old branch, maybe you have downloaded concepticon before, or whatever.

**Comment by LinguList** [comment]
So to summarize:

1. find the config file 
2. find where the concepticon-data is in your system
3. check the branch and run git pull inside the concepticon-data

**Comment by LinguList** [comment]
BTW, @AnnikaTjuka wrote on this as well [here](https://calc.hypotheses.org/2225).

**Comment by ilchec** [comment]
@LinguList It worked! Thank you!
INFO    running _cmd_makecldf on dagloans ...
INFO    file written: /Users/chechuro/Documents/Dagloans_CLDF/dagloans/cldf/.transcription-report.json
INFO    Summary for dataset /Users/chechuro/Documents/Dagloans_CLDF/dagloans/cldf/cldf-metadata.json
- **Varieties:** 175
- **Concepts:** 160
- **Lexemes:** 30,970
- **Sources:** 12
- **Synonymy:** 1.11
- **Cognacy:** 30,970 cognates in 3,549 cognate sets (1,305 singletons)
- **Cognate Diversity:** 0.11
INFO    file written: /Users/chechuro/Documents/Dagloans_CLDF/dagloans/TRANSCRIPTION.md
INFO    ... done dagloans [101.8 secs]

**Comment by LinguList** [comment]
Nice. Now you can work on the specific parts withouth having me to update! I'll close this thread now.
